version: '3'

services:
  nginx:
    image: nginx
    depends_on:
        - molgenis-red
        - molgenis-blue
    labels:
      org.molgenis.description: "A proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-config-volume:/etc/nginx/nginx.conf:ro
      - certs-volume:/etc/nginx/ssl
    networks:
      - mol-net-red
      - mol-net-blue

  molgenis-red:
    build: .
    depends_on:
        - mol-postgres-red
    networks:
      - mol-net-red
    volumes:
      - /Users/connor/Code/docker-molgenis/molgenis-blue/molgenis-server.properties:/usr/local/tomcat/molgenis-server.properties

  molgenis-blue:
    build: .
    depends_on:
        - mol-postgres-blue
    networks:
      - mol-net-blue
    volumes:
      - /Users/connor/Code/docker-molgenis/molgenis-red/molgenis-server.properties:/usr/local/tomcat/molgenis-server.properties

  mol-postgres-red:
    image: postgres
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    networks:
      - mol-net-red

  mol-postgres-blue:
    image: postgres
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    networks:
      - mol-net-blue

volumes:
  nginx-config-volume: /Users/connor/Code/docker-molgenis/nginx/myconf.conf
  certs-volume: /Users/connor/Code/docker-molgenis/nginx/certs

networks:
  mol-net-red:
  mol-net-blue:
