version: '3.1'

services:
  nginx:
    image: nginx
    depends_on:
        - molgenis-red
        - molgenis-blue
    command: ln -s /run/secrets/myconf.conf /etc/nginx/nginx.conf
    secrets:
      - nginx_conf
      - nginx_certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - red
      - blue


  molgenis-red:
    build: .
    container_name: molgenis-red
    depends_on:
        - mol-postgres-red
    networks:
      - red
    volumes:
      - /Users/connorstroomberg/Code/docker-molgenis/molgenis-red/molgenis-server.properties:/usr/local/tomcat/molgenis-server.properties

  molgenis-blue:
    build: .
    container_name: molgenis-blue
    depends_on:
        - mol-postgres-blue
    networks:
      - blue
    volumes:
      - /Users/connorstroomberg/Code/docker-molgenis/molgenis-blue/molgenis-server.properties:/usr/local/tomcat/molgenis-server.properties

  mol-postgres-red:
    image: postgres
    container_name: mol-postgres-red
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    networks:
      - red

  mol-postgres-blue:
    image: postgres
    container_name: mol-postgres-blue
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    networks:
      - blue

secrets:
  nginx_conf:
    file: ./nginx/myconf.conf
  nginx_certs:
    file: ./nginx/certs

networks:
  red:
  blue:
